### ISSUE TITLE
no-missing-template-field error for pluralizedAndtemplated

### ISSUE THREAD

**Issue by Z-42PO** [ZimbraOS/eslint-plugin-preact-i18n#4]
Hi,
I think there is a bug with eslint for preact-i18n ( https://github.com/synacor/eslint-plugin-preact-i18n/blob/HEAD/docs/rules/no-missing-template-field.md ). I do this exactly like it said :
  ```
"pluralizedAndtemplated": {
    "none": "No Things",
    "one": "One Thing",
    "many": "Many {{foo}}"
  }
```
but there is those errors : 
```
TypeError: Object.values is not a function
    at JSXElement.forEach ([PROJECT_PATH]/node_modules/eslint-plugin-preact-i18n/lib/rules/no-missing-template-field.js:61:55)
    at Array.forEach (native)
    at JSXElement ([PROJECT_PATH]/node_modules/eslint-plugin-preact-i18n/lib/rules/no-missing-template-field.js:50:43)
    at listeners.(anonymous function).forEach.listener ([PROJECT_PATH]/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (native)
    at Object.emit ([PROJECT_PATH]/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector ([PROJECT_PATH]/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors ([PROJECT_PATH]/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode ([PROJECT_PATH]/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode ([PROJECT_PATH]/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
    at nodeQueue.forEach.traversalInfo ([PROJECT_PATH]/node_modules/eslint/lib/linter.js:860:28)
```
Hope this help.

**Comment by billneff79** [comment]
@Z-42PO - Can you please paste the `<Text />` node or whatever code you have that is using this?  I need some sort of minimal reproduction to diagnose further.  There are multiple unit tests for the exact case that you point out above and they are still working in both eslint v4 and v5.  If you can submit a pull request to this repo that has a failing unit test, that would be even better.

**Comment by billneff79** [comment]
Closing for inactivity
